Refactor of notes handling for file ingridients
gogrlx/grlx pull request #56
Opened 2023-08-08 14:50 UTC by ethanholz

WIP on updates for notes handling for file ingredients.

2023-08-11 19:08 UTC, ethanholz commented
Commit [cbb8032](https://github.com/gogrlx/grlx/pull/56/commits/cbb8032609ac1dc83341eb152f044f7dd826b50b) closes numerous TODOs for adding a test handler for directrory.

2023-08-11 21:24 UTC, ethanholz commented
@taigrr requesting review for initial simple notes changes

2023-08-12 19:48 UTC, taigrr requested changes
two changes requested

2023-08-12 19:48 UTC, taigrr commented on ingredients/file/fileContent.go
> -					Changed: false, Notes: []fmt.Stringer{
Can we get a note here for the parse error? The error itself doesn't have the generated filename, for example, which could be helpful

2023-08-12 19:48 UTC, taigrr commented on ingredients/file/fileDirectory.go
> +			Notes: notes, Changed: notes != nil,
my fault but this looks incorrect, as notes will never be nil, since we declare it up above to be an empty slice

2023-08-14 16:17 UTC, ethanholz commented
@taigrr fixes added and ready for review!

2023-08-15 04:47 UTC, taigrr approved these changes

2023-08-15 04:48 UTC, merged